version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/yourssu_project
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: scripts/run-new-was.sh
      runas: ubuntu
    - location: scripts/health-check.sh
      runas: ubuntu
    - location: scripts/switch.sh
      runas: ubuntu